begin;

create table if not exists public.reply_notifications (
  id bigint generated by default as identity primary key,
  owner_guest_id text not null,
  thread_id uuid not null references public.threads(id) on delete cascade,
  reply_id bigint not null unique references public.comments(id) on delete cascade,
  parent_comment_id bigint not null references public.comments(id) on delete cascade,
  reply_preview text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists reply_notifications_owner_created_idx
  on public.reply_notifications(owner_guest_id, created_at desc);

alter table public.reply_notifications enable row level security;
revoke all on public.reply_notifications from anon, authenticated;

create or replace function public.create_direct_reply_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  parent_owner text;
begin
  if new.reply_to is null then return new; end if;

  select guest_id into parent_owner
  from public.comments
  where id = new.reply_to and thread_id = new.thread_id;

  if parent_owner is not null and parent_owner <> new.guest_id then
    insert into public.reply_notifications(
      owner_guest_id, thread_id, reply_id, parent_comment_id, reply_preview, created_at
    ) values (
      parent_owner, new.thread_id, new.id, new.reply_to, left(new.body, 180), new.created_at
    ) on conflict (reply_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists create_direct_reply_notification on public.comments;
create trigger create_direct_reply_notification
after insert on public.comments
for each row execute function public.create_direct_reply_notification();

create or replace function public.get_reply_notifications(p_guest_id text)
returns table (
  id bigint,
  thread_id uuid,
  thread_title text,
  reply_id bigint,
  reply_preview text,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_guest_id !~ '^[A-HJ-NP-Z2-9]{6}$' then
    raise exception using errcode = '22023', message = 'Invalid guest ID.';
  end if;
  return query
    select n.id, n.thread_id, t.title, n.reply_id, n.reply_preview, n.created_at, n.read_at
    from public.reply_notifications n
    join public.threads t on t.id = n.thread_id
    where n.owner_guest_id = p_guest_id
    order by n.created_at desc
    limit 20;
end;
$$;

create or replace function public.mark_reply_notification_read(p_guest_id text, p_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_guest_id !~ '^[A-HJ-NP-Z2-9]{6}$' then
    raise exception using errcode = '22023', message = 'Invalid guest ID.';
  end if;
  update public.reply_notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id and owner_guest_id = p_guest_id;
end;
$$;

create or replace function public.mark_all_reply_notifications_read(p_guest_id text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_guest_id !~ '^[A-HJ-NP-Z2-9]{6}$' then
    raise exception using errcode = '22023', message = 'Invalid guest ID.';
  end if;
  update public.reply_notifications
  set read_at = now()
  where owner_guest_id = p_guest_id and read_at is null;
end;
$$;

revoke all on function public.get_reply_notifications(text) from public;
revoke all on function public.mark_reply_notification_read(text, bigint) from public;
revoke all on function public.mark_all_reply_notifications_read(text) from public;
grant execute on function public.get_reply_notifications(text) to anon, authenticated;
grant execute on function public.mark_reply_notification_read(text, bigint) to anon, authenticated;
grant execute on function public.mark_all_reply_notifications_read(text) to anon, authenticated;

commit;
