create extension if not exists pgcrypto;

create table if not exists public.threads (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 140),
  description text check (description is null or char_length(description) <= 400),
  category text not null,
  guest_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.threads(id) on delete cascade,
  guest_id text not null,
  author_name text not null,
  side text not null default 'neutral' check (side in ('agree', 'disagree', 'neutral')),
  body text not null check (char_length(body) between 1 and 800 and body !~* '(https?://|www\.)'),
  reply_to bigint references public.comments(id) on delete set null,
  age_range text,
  country_code text,
  created_at timestamptz not null default now()
);

create table if not exists public.thread_votes (
  thread_id uuid not null references public.threads(id) on delete cascade,
  guest_id text not null,
  choice text not null check (choice in ('agree', 'disagree')),
  updated_at timestamptz not null default now(),
  primary key (thread_id, guest_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  target_type text not null check (target_type in ('thread', 'comment', 'general')),
  target_id text,
  thread_id text,
  guest_id text not null,
  created_at timestamptz not null default now()
);

create or replace view public.thread_summaries
with (security_invoker = true) as
select
  t.id,
  t.title,
  t.description,
  t.category,
  t.guest_id,
  t.created_at,
  count(distinct c.id)::integer as comment_count,
  count(distinct v.guest_id)::integer as vote_count,
  count(distinct v.guest_id) filter (where v.choice = 'agree')::integer as agree_count,
  count(distinct v.guest_id) filter (where v.choice = 'disagree')::integer as disagree_count
from public.threads t
left join public.comments c on c.thread_id = t.id
left join public.thread_votes v on v.thread_id = t.id
group by t.id;

alter table public.threads enable row level security;
alter table public.comments enable row level security;
alter table public.thread_votes enable row level security;
alter table public.reports enable row level security;

drop policy if exists "Public threads are readable" on public.threads;
create policy "Public threads are readable" on public.threads for select using (true);
drop policy if exists "Guests can create threads" on public.threads;
create policy "Guests can create threads" on public.threads for insert with check (char_length(guest_id) = 6);

drop policy if exists "Public comments are readable" on public.comments;
create policy "Public comments are readable" on public.comments for select using (true);
drop policy if exists "Guests can create comments" on public.comments;
create policy "Guests can create comments" on public.comments for insert with check (char_length(guest_id) = 6);

drop policy if exists "Public votes are readable" on public.thread_votes;
create policy "Public votes are readable" on public.thread_votes for select using (true);
drop policy if exists "Guests can create votes" on public.thread_votes;
create policy "Guests can create votes" on public.thread_votes for insert with check (char_length(guest_id) = 6);
drop policy if exists "Guests can update votes" on public.thread_votes;
create policy "Guests can update votes" on public.thread_votes for update using (char_length(guest_id) = 6) with check (char_length(guest_id) = 6);

drop policy if exists "Guests can create reports" on public.reports;
create policy "Guests can create reports" on public.reports for insert with check (char_length(guest_id) = 6);
drop policy if exists "MVP reports are readable" on public.reports;
create policy "MVP reports are readable" on public.reports for select using (true);

grant select on public.thread_summaries to anon, authenticated;
grant select, insert on public.threads to anon, authenticated;
grant select, insert on public.comments to anon, authenticated;
grant select, insert, update on public.thread_votes to anon, authenticated;
grant select, insert on public.reports to anon, authenticated;
grant usage, select on sequence public.comments_id_seq to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.thread_votes;
exception
  when duplicate_object then null;
end $$;
